# https://travis-ci.org/christoph2/pyxcp
dist: xenial
language: python
sudo: required
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev

os:
  - linux
#  - osx

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - travis_retry pip install pylint codeclimate-test-reporter
  - travis_retry pip install pytest-cov coverage coveralls codacy-coverage

script:
#  python -m unittest discover ./objutils/tests/
#   python ./objutils/tools/readelf.py
   coverage run --source=pyxcp setup.py test

after_success:
  - pylint pyxcp
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
  - codeclimate-test-reporter
