TRANSPORT = "CAN"
CAN_DRIVER = "SocketCAN"
CAN_USE_DEFAULT_LISTENER = true
CHANNEL = "vcan0"
CAN_ID_MASTER = 257
CAN_ID_SLAVE = 258
CAN_ID_BROADCAST = 256
MAX_DLC_REQUIRED = false
CREATE_DAQ_TIMESTAMPS = false
FD = false
