TRANSPORT = "CAN"
CAN_DRIVER = "Vector"
CAN_USE_DEFAULT_LISTENER = true
CHANNEL = "0"
CAN_ID_MASTER = 2
CAN_ID_SLAVE = 1
CAN_ID_BROADCAST = 256
# MAX_DLC_REQUIRED = true
CREATE_DAQ_TIMESTAMPS = false
BITRATE=1000000
SEED_N_KEY_DLL = "SeedNKeyXcp.dll"
