TRANSPORT = "CAN"
CAN_DRIVER = "KVaser"
CAN_USE_DEFAULT_LISTENER = true
CHANNEL = "0"
ACCEPT_VIRTUAL = true
CAN_ID_MASTER = 257
CAN_ID_SLAVE = 258
CAN_ID_BROADCAST = 256
MAX_DLC_REQUIRED = false
BITRATE = 50000
DATA_BITRATE = 50000
FD=false
BTL_CYCLES = 16
SAMPLE_RATE = 1
SAMPLE_POINT = 87.5
SJW = 2
TSEG1 = 5
TSEG2 = 2
CREATE_DAQ_TIMESTAMPS = false
