TRANSPORT = "CAN"
CAN_DRIVER = "SocketCAN"
CAN_USE_DEFAULT_LISTENER = true
CHANNEL = "can0"
CAN_ID_MASTER = 257
CAN_ID_SLAVE = 258
CAN_ID_BROADCAST = 256
CREATE_DAQ_TIMESTAMPS = false
FD = false
MAX_DLC_REQUIRED = true
MAX_CAN_FD_DLC = 32
PADDING_VALUE = 0
